### PR TITLE
remove CRI-O system containers

### PR DESCRIPTION
**Pull request by runcom**
We're moving the system containers bits in the CRI-O repository to ease maintainance and automate all the flow from there

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@giuseppe PTAL

**Comment by cgwalters** [comment]
Surely a PR like this could at least include a one-liner rationale for those of us not in the loop?

**Comment by runcom** [comment]
> Surely a PR like this could at least include a one-liner rationale for those of us not in the loop?

added a comment, sorry

**Comment by jasonbrooks** [comment]
Good, I was worried: https://github.com/kubernetes-incubator/cri-o/pull/1197

**Comment by giuseppe** [comment]
LGTM, I'll merge once https://github.com/kubernetes-incubator/cri-o/pull/1197 is in and I can change the location for the CentOS registry

**Comment by giuseppe** [comment]
I'll approve this PR as soon as https://github.com/CentOS/container-index/pull/241 is merged

**Comment by giuseppe** [comment]
@rh-atomic-bot r+ 566717d

**Pull request closed without merging**
