### PR TITLE
<WIP> Update runc config file for runtime-spec 1.0.0-rc5

### PR DESCRIPTION
**Pull request by yuqi-zhang**
The new runc 1.0.0-rc3 (https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc3) uses runtime-spec 1.0.0-rc5 (https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc5), which has changes to the json schema for the json file. Notably the process[capabilities] are now in sets, which breaks system containers. I'm looking into other changes as well, but this patch should be enough to work with runc 1.0.0-rc3, so I will leave it here for testing.

### CODE REVIEW

**Comment by rhatdan** [comment]
:+1:

**Comment by giuseppe** [comment]
@yuqi-zhang prepared the Docker fix as well:

https://github.com/giuseppe/atomic-system-containers/tree/prepare-docker-for-new-runc

**Comment by yuqi-zhang** [comment]
@giuseppe Should we merge this as well?

**Comment by giuseppe** [comment]
@yuqi-zhang yes, let's start merging this as well..

@rh-atomic-bot r+ 51bd1d1

**Pull request closed without merging**
