### PR TITLE
etcd: allow to specify additional bind mounts

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@ingvagabund this should allow us to replace the dirty hack for etcd in openshift-ansible, as we can specify any bind mount we like

**Comment by ashcrow** [comment]
@giuseppe does this require rebuilds for any current releases or is it forward looking?

**Comment by giuseppe** [comment]
@yuqi-zhang yes, we could do that, in the default case it won't change how they work.  Another change we will have to do for all containers is to specify the additional systemd `ExecStartPre=$EXEC_STARTPRE` and `ExecStopPost=$EXEC_STOPPOST` so that we can finally use `runc -d` instead of requiring runc running for each container.

@ingvagabund I confirm that it works with the Openshift installer, all I needed to do, was:

1) `--set=ADDTL_MOUNTS=',{"type":"bind","source":"/etc/","destination":"/etc/","options":["rbind","rw","rslave"]}'`
2) replace any `/var/lib/etcd/etc` with `/etc/etcd`
3) Specify `DATADIR=/var/lib/etcd`

**Comment by giuseppe** [comment]
@aveshagarwal how easy would be to get this change in the official etcd image (once it gets accepted)?  It is needed to drop a huge hack we are carrying in the OpenShift installer for using the etcd system container

**Comment by yuqi-zhang** [comment]
@giuseppe sounds good. We can do that in a separate PR. I can merge this once the discussion is finished.

**Comment by aveshagarwal** [comment]
@giuseppe create a bz for 7.4.1 so that I can commit these changes (config.json.template and manifest.json) in the next build.

**Comment by ashcrow** [comment]
@rh-atomic-bot r+ e62b9ec

**Pull request closed without merging**
