### PR TITLE
Docker: fix machinectl

### PR DESCRIPTION
**Pull request by giuseppe**
Add `oci-register-machine` to the Docker container so that machines are registered with systemd

### CODE REVIEW

**Comment by ashcrow** [comment]
👍 

I'll rebase https://github.com/projectatomic/atomic-system-containers/pull/59 on top of this once it's merged.

**Comment by giuseppe** [comment]
@rh-atomic-bot delegate=jwhonce

**Comment by jwhonce** [comment]
@rh-atomic-bot r+

**Comment by giuseppe** [comment]
@rh-atomic-bot  r=jwhonce d22623d

**Pull request closed without merging**
