### PR TITLE
add files for building CRI-O and Docker on the CentOS registry

### PR DESCRIPTION
**Pull request by giuseppe**
/cc @mohammedzee1000 @ashcrow

### CODE REVIEW

**Comment by giuseppe** [comment]
@rh-atomic-bot delegate=mohammedzee1000

**Comment by ashcrow** [comment]
The Upstreams section looks odd to me. Is it correct?

**Comment by giuseppe** [comment]
@ashcrow yes it looks a bit odd.  :-)  I've used the template from: https://github.com/CentOS/container-index/blob/master/cccp.yml and only customized the job-id

**Comment by ashcrow** [comment]
@giuseppe that makes sense. I did take a quick look at a few other ```cccp.yml``` files and they seem to not include that section:

- https://github.com/mohammedzee1000/postgresql_openshift/blob/master/10/cccp.yml
- https://github.com/fabric8-ui/fabric8-ui-openshift-nginx/blob/master/cccp.yml
- https://github.com/syamgk/status-api/blob/master/cccp.yml
- https://github.com/CentOS/CentOS-Dockerfiles/blob/master/Django/centos7/cccp.yml

**Comment by mohammedzee1000** [comment]
@giuseppe @ashcrow The pipeline is capable of taking default values for all optional fields, although we encourage their usage.

**Comment by mohammedzee1000** [comment]
@rh-atomic-bot r+ bb18074

**Pull request closed without merging**
