### PR TITLE
CRI-O: copy the plugins from /usr/libexec/cni

### PR DESCRIPTION
**Pull request by giuseppe**
Sync with a change in the .rpm

### CODE REVIEW

**Comment by giuseppe** [comment]
@rh-atomic-bot r=lsm5

@lsm5

**Comment by giuseppe** [comment]
@rh-atomic-bot cancel

**Comment by giuseppe** [comment]
By mistake I've merged this PR before a review (I thought of using `delegate=` instead I typed `r=`) and I wasn't quick enough to cancel it.

The change is trivial enough, if there are comments I'll address them in a separate PR.

**Comment by lsm5** [comment]
lgtm, thanks :)

**Pull request closed without merging**
