### PR TITLE
docker: ensure Docker runs with label system_u:system_r:container_runtime_t:s0

### PR DESCRIPTION
**Pull request by giuseppe**

### CODE REVIEW

**Comment by ashcrow** [comment]
@giuseppe is the following runc version workable with the spec change?

```
runc version 1.0.0-rc3
commit: cafb8d8755dc2b990fc73fbf7bff62f534da9219-dirty
spec: 1.0.0-rc5
```

**Comment by ashcrow** [comment]
@rh-atomic-bot r+ 978c149

**Comment by yuqi-zhang** [comment]
ack, thanks!

**Pull request closed without merging**
