### PR TITLE
crio: do not use --log-level=debug by default

### PR DESCRIPTION
**Pull request by giuseppe**

### CODE REVIEW

**Comment by giuseppe** [comment]
@rh-atomic-bot r=mrunalp

**Comment by ashcrow** [comment]
@giuseppe / @mrunalp: I assume this is not a must have for the current set of work?

**Comment by mrunalp** [comment]
@ashcrow Yes, it isn't. This is to address a bug that QE opened as it doesn't make sense to deploy to prod with debugs enabled.

**Comment by ashcrow** [comment]
@mrunalp cool, thanks!

**Comment by runcom** [comment]
LGTM

**Comment by ashcrow** [comment]
@rh-atomic-bot r+ d57c705

**Pull request closed without merging**
