### PR TITLE
Add labels to etcd and flannel

### PR DESCRIPTION
**Pull request by yuqi-zhang**
Add initial labels to etcd and flannel with reference to the fedora
registry guidelines.

Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
As per discussion with @dustymabe @giuseppe @maxamillion we will try to move this into the fedora container registry, so users can pull/test/use from an "official" repo.

This is a tentative initial label, notably that the bugzilla component is "etcd-docker" and "flannel-docker", same as their rhel counterparts.

**Comment by ashcrow** [comment]
Here is the [documentation reference](https://fedoraproject.org/wiki/Container:Guidelines#LABELS) for those interested.

**Comment by giuseppe** [comment]
Great work!  @ashcrow, thanks for the review :)

@rh-atomic-bot r=ashcrow bda79c3

**Comment by rhatdan** [comment]
@giuseppe did you add new LABEL to allow atomic command to automatically set the --system flag?

**Comment by giuseppe** [comment]
I opened a PR to add it for flannel:

https://github.com/projectatomic/atomic-system-containers/pull/31

**Comment by rhatdan** [comment]
Thanks

**Pull request closed without merging**
