### PR TITLE
tests: verify JSON files are valid

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
What is this trying to catch specifically? Let's say if I'm missing a comma somewhere in the json file, the lint file will return something like: `ValueError: Expecting , delimiter: line 22 column 4 (char 393)` and this never gets run. If I move this above the lint tests and there is an error, it just boots me out of root.

**Comment by giuseppe** [comment]
@yuqi-zhang good point.  I've moved it above and dropped the quiet flag so we will get a better and more helpful error message when it fails.  What do you think?

**Comment by yuqi-zhang** [comment]
I feel that the error message isn't very descriptive:

> JSON is valid
JSON is valid
JSON is valid
JSON is valid
parse error: after array element, I expect ',' or ']'
                                        { 	"ociVersion": "1.0.0", 	"pl
                     (right here) ------^
JSON is invalid

Also boots me out of root still, which is a minor annoyance.
Sorry for the nits.

**Comment by giuseppe** [comment]
thanks for the review, I've added the file name to the output now

**Comment by yuqi-zhang** [comment]
I think this is better than the old error that you would see.

@rh-atomic-bot r+ 415caf0

**Pull request closed without merging**
