### PR TITLE
ovirt-guest-agent: Drop the hibernate wrapper

### PR DESCRIPTION
**Pull request by vinzenz**
Addresses the comments about the hibernate script from PR #36 after it was merged

Signed-off-by: Vinzenz Feenstra <vfeenstr@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
the patch LGTM.  Should we drop the suspend script as well?

**Comment by vinzenz** [comment]
Not sure which you mean :-) hibernate and suspend is done by the same script :-)

**Comment by giuseppe** [comment]
I see there is a ovirt-container-shutdown.sh file left in the container.  Can we drop it as well?

**Comment by vinzenz** [comment]
No we can't otherwise the agent won't be able to reboot the host. 

`# shutdown -h now

Running in chroot, ignoring request.`

**Comment by giuseppe** [comment]
I see.  Thanks for the explanation, I think it is safe to assume /sbin/shutdown is present on the host. Going to merge this:

@rh-atomic-bot r+ 66b05bf

**Pull request closed without merging**
