### PR TITLE
flannel: allow devices

### PR DESCRIPTION
**Pull request by giuseppe**
we are already bind mounting /dev, so allow devices to be used inside
the container.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by ashcrow** [comment]
@rh-atomic-bot r+ 8ddfbeeeb5e9f991abeb8428d854a66e01e5ba94

**Comment by ashcrow** [comment]
@rh-atomic-bot retry

**Comment by ashcrow** [comment]
This again. I thought we have a workaround already in place?
```
  Running scriptlet: guile-5:2.0.14-1.fc26.x86_64                         85/85BDB1539 Build signature doesn't match environment
```

**Comment by giuseppe** [comment]
yes, we have it.

@jlebon do you know if something changed?

**Comment by jlebon** [comment]
Yeah, this is a variant of the same caused by:

```
 Downgrading:
 glibc                    x86_64   2.25-9.fc26                  updates   3.4 M
 glibc-common             x86_64   2.25-9.fc26                  updates   889 k
 glibc-langpack-en        x86_64   2.25-9.fc26                  updates   290 k
 libcrypt-nss             x86_64   2.25-9.fc26                  updates    53 k
```

Try `distro-sync` instead. See: https://github.com/ostreedev/ostree/pull/1190.

**Comment by giuseppe** [comment]
yes!  distro-sync helped

**Comment by ashcrow** [comment]
@rh-atomic-bot retry

**Comment by giuseppe** [comment]
@ashcrow I think it needs r+ with the new commit checksum

**Comment by ashcrow** [comment]
@rh-atomic-bot r+ df7ee2b

**Pull request closed without merging**
