### PR TITLE
CRI-O: set rootfsPropagation to rslave

### PR DESCRIPTION
**Pull request by giuseppe**
so that the CRI-O container can see the mount points from node when it is running on the host.

It addresses this issue: https://github.com/openshift/openshift-ansible/pull/4898#issuecomment-319462397

@ashcrow I've already built the CentOS based image on Docker hub on top of this PR.

the router is deployed correctly but I am seeing that the registry gets stuck, I am still investigating if it depends from the system container

### CODE REVIEW

**Comment by giuseppe** [comment]
nevermind my previous comment, it was a configuration problem in my inventory file, so it should be ready to go

**Comment by ashcrow** [comment]
I'll do a test run now!

**Comment by ashcrow** [comment]
With selinux off the errors still occur. I tried deleting and recreating the pods, restarting ``cri-o``, rebooting the vm, restarting openvswitch, etc... All end up with the following issue:

```
Aug 03 11:58:47 localhost.localdomain atomic-openshift-node[1484]: E0803 11:58:47.699533    1484 pod_workers.go:182] Error syncing pod a21ae10f-7864-11e7-accd-525400148717 ("router-1-deploy_default(a21ae10f-7864-11e7-accd-525400148717)"), skipping: failed to "CreatePodSandbox" for "router-1-deploy_default(a21ae10f-7864-11e7-accd-525400148717)" with CreatePodSandboxError: "CreatePodSandbox for pod \"router-1-deploy_default(a21ae10f-7864-11e7-accd-525400148717)\" failed: rpc error: code = 2 desc = failed to create network for container k8s_infra_router-1-deploy_default_a21ae10f-7864-11e7-accd-525400148717_0 in sandbox 0b61899dcd9ffa4abc538819de0d8e64b5a411158d2e4739ed02bca6d378a643: CNI request failed with status 400: 'unknown FS magic on \"/var/run/netns/k8s_router-1-deploy_default_a21ae10f-7864-11e7-accd-525400148717_0-032e223d\": 1021994\n'"
```

**Comment by ashcrow** [comment]
The error looks similar to https://github.com/kubernetes-incubator/cri-o/issues/438

On the host I see creation of files like:

```
cni-a24a96d7-9755-3c46-d69e-de5feec3b901
k8s_router-1-deploy_default_2b82adb4-7868-11e7-a906-525400148717_0-6e6a27d8
```

which are deleted very quickly. The system container doesn't look like it mounts this directory. I added this to the ``config.json`` but no change happened upon restart:

```
        {
            "type": "bind",
            "source": "/var/run",
            "destination": "/var/run",
            "options": [
                "rshared",
                "rbind",
                "rw",
                "mode=755"
            ]
        },
```

Of course ``/run`` is already mounted and also show up there ...

**Comment by giuseppe** [comment]
The issue was solved for me by the new set_mounts.sh and the rootfsPropagation set to rslave, could you please double check that the rootfsPropagation is correct in the config.json and the propagation for /var/lib is "shared"?  If you share the latest inventory file you have used, I will try to reproduce the issue here.

**Comment by ashcrow** [comment]
@giuseppe 

```
shared        └─/var/lib
```

In config.json:
```
        "rootfsPropagation": "rslave",
```

**Comment by ashcrow** [comment]
@giuseppe sent the inventory via email.

**Comment by ashcrow** [comment]
I get the exact same error using a totally fresh install 😦 

```
Aug 03 17:03:01 localhost.localdomain atomic-openshift-node[10488]: E0803 17:03:01.032868   10488 pod_workers.go:182] Error syncing pod 3fa9506b-788e-11e7-9b7a-525400c66acb ("router-1-deploy_default(3fa9506b-788e-11e7-9b7a-525400c66acb)"), skipping: failed to "CreatePodSandbox" for "router-1-deploy_default(3fa9506b-788e-11e7-9b7a-525400c66acb)" with CreatePodSandboxError: "CreatePodSandbox for pod \"router-1-deploy_default(3fa9506b-788e-11e7-9b7a-525400c66acb)\" failed: rpc error: code = 2 desc = failed to create network for container k8s_infra_router-1-deploy_default_3fa9506b-788e-11e7-9b7a-525400c66acb_0 in sandbox bb32c19120d4e93d12ed2c8d94493116b26e90511406367f8b04b7831df17c60: CNI request failed with status 400: 'unknown FS magic on \"/var/run/netns/k8s_router-1-deploy_default_3fa9506b-788e-11e7-9b7a-525400c66acb_0-a2f0e625\": 1021994\n'"
```

**Comment by ashcrow** [comment]
This works as expected. I'm able to fully install via a gold RHEL 7.4 install. During testing I noticed s2i builds fail in origin, but I think that is outside of this work. Running premade containers works exactly as it should (tested with mysql-ephemeral).

👍

**Comment by ashcrow** [comment]
@rh-atomic-bot r+ 0c68898

**Pull request closed without merging**
