### PR TITLE
Docker fix config.json

### PR DESCRIPTION
**Pull request by giuseppe**

### CODE REVIEW

**Comment by rhatdan** [comment]
Not sure what you are doing here?

**Comment by giuseppe** [comment]
it seems the problem was using "rbind" instead of "bind" for the mount type.  While it is accepted and everything runs correctly, it is confusing for runc to understand /dev is coming from the host and so to not touch /dev/ptmx.

**Comment by rhatdan** [comment]
We should fix runc to not be specific to bind, but also handle rbind.

**Comment by rhatdan** [comment]
@mrunalp PTAL

**Comment by rhatdan** [comment]
@giuseppe what about the SELinux label changes?

**Comment by giuseppe** [comment]
AFAICS, rbind is an option of the bind type; so it is handled.

**Comment by giuseppe** [comment]
the labels have no effect after we moved to "container_runtime_t" for runc and "container_share_t" for the containers data

**Comment by mrunalp** [comment]
LGTM

**Comment by rhatdan** [comment]
Probably should be 

"selinuxProcessLabel": "system_u:system_r:container_runtime_t:s0" 

But with this label, you are not seeing docker running as container_runtime_t?  How about if you run in permissive mode?

Are you seeing any AVCs?  ausearch -m avc -ts recent.

Break the pull request in two without the SELinux stuff and then you can merge. I am thinking something else is preventing the container_runtime_t from working.

**Comment by giuseppe** [comment]
I've moved the SELinux patches here: https://github.com/projectatomic/atomic-system-containers/pull/17

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
Oops that does not work here.
LGTM

**Comment by giuseppe** [comment]
we have homu integration for this project, not idea why it didn't get your r+

**Comment by cgwalters** [comment]
rhatdan is now an approver here.  See also https://github.com/servo/homu/issues/34

**Comment by rhatdan** [comment]
Ok sorry about that.

**Pull request merged**
