### PR TITLE
Multiple linter updates

### PR DESCRIPTION
**Pull request by ashcrow**
- Update the linter to pass most of standard Python linting
- Fix output when ``golang`` is missing

### CODE REVIEW

**Comment by ashcrow** [comment]
Reminder @themurph and @yuqi-zhang

**Comment by giuseppe** [comment]
@ashcrow, LGTM, can I r+ it?

**Comment by ashcrow** [comment]
@giuseppe go for it!

**Comment by yuqi-zhang** [comment]
Sorry for the late response. LGTM here as well.

@rh-atomic-bot r+ d33e44c

**Pull request closed without merging**
